services:
  db:
    image: postgres:16
    container_name: pinnacle-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pinnacle
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
