include: package:flutter_lints/flutter.yaml
formatter:
  trailing_commas: preserve
linter:
  rules:
    avoid_print: false
analyzer:
  errors:
    # Treat these specific issues as info or ignore them completely
    constant_identifier_names: ignore
