export enum Sector {
  ALL_SECTORS = 'ALL_SECTORS',
  ANALYTICS = 'ANALYTICS',
  CONSULTING = 'CONSULTING',
  COMPUTER_SCIENCE_SOFTWARE_IT = 'COMPUTER_SCIENCE_SOFTWARE_IT',
  E_COMMERCE = 'E_COMMERCE',
  EDUCATION = 'EDUCATION',
  ENGINEERING_TECHNOLOGY = 'ENGINEERING_TECHNOLOGY',
  FINANCE_BFSI = 'FINANCE_BFSI',
  FMCG = 'FMCG',
  HEALTHCARE = 'HEALTHCARE',
  MEDIA_ENTERTAINMENT = 'MEDIA_ENTERTAINMENT',
  RESEARCH_DEVELOPMENT = 'RESEARCH_DEVELOPMENT',
  TELECOM = 'TELECOM',
  ENERGY = 'ENERGY',
  MANUFACTURING_TECHNOLOGY = 'MANUFACTURING_TECHNOLOGY',
  OTHERS = 'OTHERS',
}

export enum ApplicationStatus {
  APPLIED = 'APPLIED',
  SHORTLISTED = 'SHORTLISTED',
  INTERVIEWING = 'INTERVIEWING',
  REJECTED = 'REJECTED',
  HIRED = 'HIRED',
  WITHDRAWN = 'WITHDRAWN',
}
